version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    command: ["run", "mistral"]

  faiss-api:
    build: ./faiss-api
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  streamlit-ui:
    build: ./streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - faiss-api

volumes:
  ollama: